# Generated by Django 4.0.6 on 2022-08-04 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('complement', models.CharField(max_length=255)),
                ('location_wgs84', models.CharField(max_length=255, null=True)),
                ('location_lv95', models.CharField(max_length=20, null=True)),
                ('type', models.CharField(max_length=100)),
                ('has_been_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('gestsis_key', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'sis',
            },
        ),
        migrations.CreateModel(
            name='Firefighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('group_number', models.CharField(max_length=20, null=True)),
                ('fullname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firefighters', to='mail_parser.alarm')),
                ('sis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail_parser.sis')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail_parser.alarm')),
            ],
        ),
        migrations.AddField(
            model_name='alarm',
            name='sis',
            field=models.ManyToManyField(to='mail_parser.sis'),
        ),
        migrations.AddConstraint(
            model_name='firefighter',
            constraint=models.UniqueConstraint(fields=('fullname', 'sis', 'group_name', 'group_number', 'phone', 'alarm'), name='unique_firefighter'),
        ),
    ]
