# Generated by Django 4.0.5 on 2022-06-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_parser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='sis_id',
        ),
        migrations.AddField(
            model_name='alarm',
            name='sis',
            field=models.ManyToManyField(to='mail_parser.sis'),
        ),
    ]
