version: '3'

services:
  gestsis_alarm:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: gestsis_alarm
    volumes:
      - .:/gestsis_alarm
    ports:
      - "8000:8000"
