# Generated by Django 4.0.5 on 2022-06-29 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('location_wgs84', models.CharField(max_length=255)),
                ('location_lv95', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=100)),
                ('has_been_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gestsis_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Firefighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=255)),
                ('fullname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('alarm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail_parser.alarm')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('alarm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail_parser.alarm')),
            ],
        ),
        migrations.AddField(
            model_name='alarm',
            name='sis_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail_parser.sis'),
        ),
    ]
