# Generated by Django 4.0.5 on 2022-06-29 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail_parser', '0002_remove_alarm_sis_id_alarm_sis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='alarm_id',
            new_name='alarm',
        ),
        migrations.RemoveField(
            model_name='firefighter',
            name='alarm_id',
        ),
        migrations.AddField(
            model_name='alarm',
            name='firefighter',
            field=models.ManyToManyField(to='mail_parser.firefighter'),
        ),
        migrations.AddField(
            model_name='firefighter',
            name='sis',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mail_parser.sis'),
            preserve_default=False,
        ),
    ]
