# Generated by Django 4.0.5 on 2022-06-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_parser', '0003_rename_alarm_id_file_alarm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='complement',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
