# Generated by Django 4.0.5 on 2022-06-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_parser', '0004_alarm_complement'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='firefighter',
            constraint=models.UniqueConstraint(fields=('fullname', 'sis', 'group', 'phone'), name='unique_firefighter'),
        ),
    ]
