# Generated by Django 4.0.5 on 2022-06-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_parser', '0005_firefighter_unique_firefighter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
