# Generated by Django 4.0.5 on 2022-07-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_parser', '0006_alter_file_filename'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='firefighter',
            name='unique_firefighter',
        ),
        migrations.RenameField(
            model_name='firefighter',
            old_name='group',
            new_name='group_name',
        ),
        migrations.AddField(
            model_name='firefighter',
            name='group_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='firefighter',
            constraint=models.UniqueConstraint(fields=('fullname', 'sis', 'group_name', 'group_number', 'phone'), name='unique_firefighter'),
        ),
    ]
