# Generated by Django 4.0.5 on 2022-07-04 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_parser', '0007_remove_firefighter_unique_firefighter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sis',
            old_name='gestsis_name',
            new_name='gestsis_key',
        ),
    ]
