# Generated by Django 4.0.5 on 2022-07-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_parser', '0008_rename_gestsis_name_sis_gestsis_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sis',
            name='gestsis_key',
            field=models.CharField(max_length=10),
        ),
    ]
