# Generated by Django 4.0.5 on 2022-07-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_parser', '0009_alter_sis_gestsis_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='location_lv95',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='location_wgs84',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
