# Generated by Django 4.0.6 on 2022-07-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_parser', '0010_alter_alarm_location_lv95_alter_alarm_location_wgs84'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sis',
            name='gestsis_key',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='sis',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
