# Generated by Django 4.0.6 on 2022-07-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_parser', '0011_alter_sis_gestsis_key_alter_sis_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sis',
            options={'verbose_name_plural': 'sis'},
        ),
    ]
