"""
Django settings for gestsis_alarm project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import environ
import os.path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    GESTSIS_ALARM_DEBUG_MODE=(bool, False)
)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


SECRET_KEY = env('GESTSIS_ALARM_SECRET_KEY')

DEBUG = env('GESTSIS_ALARM_DEBUG_MODE')

ALLOWED_HOSTS = env.list('GESTSIS_ALARM_ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mail_parser',
    'admin_panel',
    'rest_framework'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTStatelessUserAuthentication',
    )
}

SIMPLE_JWT = {
    'ALGORITHM': "RS256",
    'JTI_CLAIM': None,
    'TOKEN_TYPE_CLAIM': None,
    'USER_ID_CLAIM': 'data',
    'ISSUER': 'GestSIS_Auth',
    "VERIFYING_KEY": open(env('GESTSIS_JWT_PUBLIC_KEY_PATH')).read(),
    'TOKEN_USER_CLASS': 'admin_panel.models.TokenUser'
}

ROOT_URLCONF = 'gestsis_alarm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestsis_alarm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DB_URL = env.db_url("GESTSIS_DATABASE_URL")

DB_NAME = (os.path.join(BASE_DIR, DB_URL.get('NAME'))
           if DB_URL.get('NAME').startswith('./') and DB_URL.get('ENGINE') == "django.db.backends.sqlite3"
           else DB_URL.get('NAME'))

DATABASES = {
    'default': {
        'ENGINE': DB_URL.get('ENGINE'),
        'NAME': DB_NAME,
        'USER': DB_URL.get('USER'),
        'PASSWORD': DB_URL.get('PASSWORD'),
        'HOST': DB_URL.get('HOST'),
        'PORT': DB_URL.get('PORT'),
        'OPTIONS': {
            "use_pure": True
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Storage files

MEDIA_ROOT = os.path.join(BASE_DIR, 'storage')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}][{asctime}][{module}][PID {process:d}] {message}',
            'style': '{',
        },
    },
    "handlers": {
        "file": {
            "class": "logging.FileHandler",
            "filename": "gestsis_alarm.log",
            'formatter': 'verbose'
        }
    },
    "loggers": {
        "main": {
            "handlers": ["file"],
            "level": 'DEBUG',
            "propagate": True
        }
    }
}